In [32]:
import pandas as pd
import numpy as np


df = pd.read_csv("/content/Day10_Flight_Operations_Dataset.csv")

print("Dataset loaded successfully!")
print(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns")

Dataset loaded successfully!
Shape: 180 rows x 17 columns

In [33]:
print(df.head())

  Flight_ID Flight_Date    Airline    Origin Destination     Aircraft  \
0    FL0001  2026-03-23   SpiceJet    Mumbai   Bengaluru  Airbus A319
1    FL0002  2026-06-07  Akasa Air     Delhi      Mumbai   Boeing 737
2    FL0003  2026-05-12  Air India     Kochi       Delhi   Boeing 737
3    FL0004  2026-05-30  Akasa Air  Srinagar       Delhi  Airbus A319
4    FL0005  2026-02-27  Air India      Pune       Delhi  Airbus A319

      Travel_Class  Passengers  Seat_Capacity  Average_Ticket_Price  \
0          Economy         210            180                  6894
1          Economy          70            210                  4468
2          Economy          67            220                  4713
3          Economy         153            220                  3791
4  Premium Economy         178            180                  6505

   Delay_Minutes Flight_Status Weather       Booking_Channel  Avg_Baggage_Kg  \
0           50.0       Delayed   Storm  Online Travel Portal              23
1            0.0       On Time     Fog         Travel Agency              16
2            5.0       On Time    Rain         Travel Agency              19
3           35.0       Delayed   Storm         Travel Agency              18
4           20.0       Delayed  Cloudy       Airline Website              25

  Meal_Preference  Passenger_Satisfaction
0         No Meal                       3
1           Vegan                       5
2         No Meal                       2
3         No Meal                       2
4         No Meal                       5

In [34]:
print(df.tail())
print(df.info())

    Flight_ID Flight_Date    Airline     Origin Destination     Aircraft  \
175    FL0176  2026-04-10     IndiGo  Ahmedabad   Bengaluru  Airbus A320
176    FL0177  2026-02-17    Vistara    Chennai      Mumbai  Airbus A320
177    FL0178  2026-04-30     IndiGo      Delhi      Mumbai  Airbus A319
178    FL0179  2026-05-08    Vistara  Bengaluru       Kochi  Airbus A320
179    FL0180  2026-01-22  Akasa Air      Delhi      Mumbai  Airbus A321

    Travel_Class  Passengers  Seat_Capacity  Average_Ticket_Price  \
175      Economy          48            189                  4298
176     Business         124            180                 17306
177      Economy         112            186                  4490
178      Economy         134            189                  5413
179      Economy         144            210                  3767

     Delay_Minutes Flight_Status Weather       Booking_Channel  \
175            0.0       On Time   Storm            Mobile App
176           20.0       Delayed  Cloudy            Mobile App
177          110.0       Delayed     Fog  Online Travel Portal
178           20.0       Delayed    Rain  Online Travel Portal
179           75.0       Delayed     Fog  Online Travel Portal

     Avg_Baggage_Kg Meal_Preference  Passenger_Satisfaction
175              11      Vegetarian                       5
176               8         No Meal                       5
177              16      Vegetarian                       3
178               9         No Meal                       2
179              17         No Meal                       5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB
None

In [35]:
print(df.dtypes)

Flight_ID                  object
Flight_Date                object
Airline                    object
Origin                     object
Destination                object
Aircraft                   object
Travel_Class               object
Passengers                  int64
Seat_Capacity               int64
Average_Ticket_Price        int64
Delay_Minutes             float64
Flight_Status              object
Weather                    object
Booking_Channel            object
Avg_Baggage_Kg              int64
Meal_Preference            object
Passenger_Satisfaction      int64
dtype: object

In [36]:
df.describe()

,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Avg_Baggage_Kg,Passenger_Satisfaction
count,180.000000,180.000000,180.000000,173.000000,180.000000,180.000000
mean,122.772222,197.238889,6111.677778,19.335260,15.150000,3.494444
std,45.635651,15.408176,3615.220040,29.029712,5.705506,1.169908
min,45.000000,180.000000,1949.000000,0.000000,5.000000,2.000000
25%,78.750000,186.000000,3815.500000,0.000000,10.000000,2.000000
50%,125.000000,189.000000,5380.000000,5.000000,15.500000,3.000000
75%,162.250000,210.000000,6790.000000,20.000000,20.000000,5.000000
max,210.000000,220.000000,27832.000000,110.000000,25.000000,5.000000

In [37]:
categorical_cols = ["Airline", "Origin", "Destination", "Aircraft",
                    "Travel_Class", "Flight_Status", "Weather",
                    "Booking_Channel", "Meal_Preference"]

for col in categorical_cols:
    print(f"{col} ({df[col].nunique()} unique): {sorted(df[col].unique())}")
    print("-" * 100)

Airline (6 unique): ['Air India', 'Air India Express', 'Akasa Air', 'IndiGo', 'SpiceJet', 'Vistara']
----------------------------------------------------------------------------------------------------
Origin (11 unique): ['Ahmedabad', 'Bengaluru', 'Chennai', 'Delhi', 'Hyderabad', 'Jaipur', 'Kochi', 'Lucknow', 'Mumbai', 'Pune', 'Srinagar']
----------------------------------------------------------------------------------------------------
Destination (8 unique): ['Bengaluru', 'Chennai', 'Delhi', 'Hyderabad', 'Kochi', 'Kolkata', 'Mumbai', 'Srinagar']
----------------------------------------------------------------------------------------------------
Aircraft (4 unique): ['Airbus A319', 'Airbus A320', 'Airbus A321', 'Boeing 737']
----------------------------------------------------------------------------------------------------
Travel_Class (3 unique): ['Business', 'Economy', 'Premium Economy']
----------------------------------------------------------------------------------------------------
Flight_Status (3 unique): ['Cancelled', 'Delayed', 'On Time']
----------------------------------------------------------------------------------------------------
Weather (5 unique): ['Clear', 'Cloudy', 'Fog', 'Rain', 'Storm']
----------------------------------------------------------------------------------------------------
Booking_Channel (4 unique): ['Airline Website', 'Mobile App', 'Online Travel Portal', 'Travel Agency']
----------------------------------------------------------------------------------------------------
Meal_Preference (4 unique): ['No Meal', 'Non-Vegetarian', 'Vegan', 'Vegetarian']
----------------------------------------------------------------------------------------------------

In [38]:
df.isnull().sum()

Flight_ID                 0
Flight_Date               0
Airline                   0
Origin                    0
Destination               0
Aircraft                  0
Travel_Class              0
Passengers                0
Seat_Capacity             0
Average_Ticket_Price      0
Delay_Minutes             7
Flight_Status             0
Weather                   0
Booking_Channel           0
Avg_Baggage_Kg            0
Meal_Preference           0
Passenger_Satisfaction    0
dtype: int64

In [39]:
df[df["Delay_Minutes"].isnull()]

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
23,FL0024,2026-05-19,SpiceJet,Ahmedabad,Bengaluru,Airbus A319,Economy,110,186,5578,NaN,Cancelled,Rain,Travel Agency,9,Vegetarian,3
37,FL0038,2026-03-27,Air India,Delhi,Srinagar,Airbus A320,Economy,166,210,5972,NaN,Cancelled,Rain,Travel Agency,5,Non-Vegetarian,5
40,FL0041,2026-03-23,Akasa Air,Delhi,Chennai,Airbus A321,Economy,170,189,4013,NaN,Cancelled,Fog,Travel Agency,13,No Meal,3
65,FL0066,2026-03-06,SpiceJet,Srinagar,Delhi,Airbus A320,Economy,83,210,4418,NaN,Cancelled,Cloudy,Travel Agency,19,Vegetarian,5
68,FL0069,2026-03-09,SpiceJet,Kochi,Delhi,Airbus A321,Economy,107,186,5911,NaN,Cancelled,Cloudy,Online Travel Portal,23,Non-Vegetarian,5
110,FL0111,2026-05-16,Vistara,Delhi,Mumbai,Airbus A321,Premium Economy,124,186,6711,NaN,Cancelled,Cloudy,Mobile App,19,Vegetarian,4
160,FL0161,2026-04-03,Vistara,Delhi,Mumbai,Airbus A320,Economy,135,220,6154,NaN,Cancelled,Storm,Mobile App,6,Vegetarian,2

In [40]:
df["Delay_Minutes"] = df["Delay_Minutes"].fillna(0)

print("Duplicate rows:", df.duplicated().sum())

df.isnull().sum().sum()

Duplicate rows: 0

np.int64(0)

In [41]:
df["Load_Factor_%"] = round((df["Passengers"] / df["Seat_Capacity"]) * 100, 2)

df["Revenue"] = df["Passengers"] * df["Average_Ticket_Price"]

df["Flight_Date"] = pd.to_datetime(df["Flight_Date"])
df["Month"] = df["Flight_Date"].dt.month_name()
df["Day_of_Week"] = df["Flight_Date"].dt.day_name()

def delay_bucket(minutes):
    if minutes == 0:
        return "No Delay"
    elif minutes <= 30:
        return "Minor Delay (<=30 min)"
    elif minutes <= 60:
        return "Moderate Delay (31-60 min)"
    else:
        return "Severe Delay (>60 min)"

df["Delay_Category"] = df["Delay_Minutes"].apply(delay_bucket)

df.head()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,...,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction,Load_Factor_%,Revenue,Month,Day_of_Week,Delay_Category
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,...,Storm,Online Travel Portal,23,No Meal,3,116.67,1447740,March,Monday,Moderate Delay (31-60 min)
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,...,Fog,Travel Agency,16,Vegan,5,33.33,312760,June,Sunday,No Delay
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,...,Rain,Travel Agency,19,No Meal,2,30.45,315771,May,Tuesday,Minor Delay (<=30 min)
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,...,Storm,Travel Agency,18,No Meal,2,69.55,580023,May,Saturday,Moderate Delay (31-60 min)
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,...,Cloudy,Airline Website,25,No Meal,5,98.89,1157890,February,Friday,Minor Delay (<=30 min)

In [42]:
ops_view = df[["Flight_ID", "Airline", "Origin", "Destination",
               "Flight_Status", "Delay_Minutes", "Weather"]]

ops_view.head()

,Flight_ID,Airline,Origin,Destination,Flight_Status,Delay_Minutes,Weather
0,FL0001,SpiceJet,Mumbai,Bengaluru,Delayed,50.0,Storm
1,FL0002,Akasa Air,Delhi,Mumbai,On Time,0.0,Fog
2,FL0003,Air India,Kochi,Delhi,On Time,5.0,Rain
3,FL0004,Akasa Air,Srinagar,Delhi,Delayed,35.0,Storm
4,FL0005,Air India,Pune,Delhi,Delayed,20.0,Cloudy

In [43]:
storm_delays = df[(df["Flight_Status"] == "Delayed") & (df["Weather"] == "Storm")]

print(f"Flights delayed due to storms: {len(storm_delays)}")
storm_delays[["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes"]]

Flights delayed due to storms: 11

    Flight_ID            Airline     Origin Destination  Delay_Minutes
0      FL0001           SpiceJet     Mumbai   Bengaluru           50.0
3      FL0004          Akasa Air   Srinagar       Delhi           35.0
29     FL0030           SpiceJet      Delhi    Srinagar           75.0
43     FL0044  Air India Express  Bengaluru   Hyderabad           35.0
54     FL0055             IndiGo      Delhi     Chennai           50.0
58     FL0059  Air India Express      Delhi    Srinagar           20.0
104    FL0105            Vistara      Delhi      Mumbai           50.0
156    FL0157          Akasa Air      Delhi    Srinagar           35.0
159    FL0160            Vistara    Lucknow       Delhi           75.0
170    FL0171           SpiceJet  Ahmedabad   Bengaluru           20.0
172    FL0173           SpiceJet   Srinagar       Delhi           75.0

In [44]:
premium_happy = df[(df["Travel_Class"] == "Business") & (df["Passenger_Satisfaction"] >= 4)]

print(f"Business class flights with satisfaction >= 4: {len(premium_happy)}")
premium_happy[["Flight_ID", "Airline", "Average_Ticket_Price", "Passenger_Satisfaction"]].head()

Business class flights with satisfaction >= 4: 5

    Flight_ID            Airline  Average_Ticket_Price  Passenger_Satisfaction
7      FL0008          Air India                 14173                       5
32     FL0033          Akasa Air                 17625                       4
132    FL0133             IndiGo                 15324                       4
138    FL0139  Air India Express                 27832                       4
176    FL0177            Vistara                 17306                       5

In [45]:
cancelled_flights = df[df["Flight_Status"] == "Cancelled"]
cancelled_flights[["Flight_ID", "Airline", "Origin", "Destination", "Weather", "Flight_Date"]]

    Flight_ID    Airline     Origin Destination Weather Flight_Date
23     FL0024   SpiceJet  Ahmedabad   Bengaluru    Rain  2026-05-19
37     FL0038  Air India      Delhi    Srinagar    Rain  2026-03-27
40     FL0041  Akasa Air      Delhi     Chennai     Fog  2026-03-23
65     FL0066   SpiceJet   Srinagar       Delhi  Cloudy  2026-03-06
68     FL0069   SpiceJet      Kochi       Delhi  Cloudy  2026-03-09
110    FL0111    Vistara      Delhi      Mumbai  Cloudy  2026-05-16
160    FL0161    Vistara      Delhi      Mumbai   Storm  2026-04-03

In [46]:
df.sort_values("Delay_Minutes", ascending=False).head(10)[
    ["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes", "Weather"]
]

    Flight_ID            Airline     Origin Destination  Delay_Minutes Weather
50     FL0051          Air India      Delhi      Mumbai          110.0    Rain
26     FL0027           SpiceJet  Bengaluru   Hyderabad          110.0   Clear
82     FL0083  Air India Express    Lucknow       Delhi          110.0  Cloudy
57     FL0058             IndiGo  Hyderabad     Kolkata          110.0  Cloudy
177    FL0178             IndiGo      Delhi      Mumbai          110.0     Fog
128    FL0129           SpiceJet    Lucknow       Delhi          110.0  Cloudy
169    FL0170             IndiGo     Mumbai     Kolkata          110.0    Rain
161    FL0162          Air India  Hyderabad     Kolkata          110.0    Rain
146    FL0147             IndiGo     Mumbai     Kolkata          110.0    Rain
21     FL0022            Vistara      Kochi       Delhi           75.0   Clear

In [47]:
df.sort_values("Revenue", ascending=False).head(10)[
    ["Flight_ID", "Airline", "Passengers", "Average_Ticket_Price", "Revenue"]
]

    Flight_ID            Airline  Passengers  Average_Ticket_Price  Revenue
138    FL0139  Air India Express         169                 27832  4703608
92     FL0093  Air India Express         209                 12970  2710730
132    FL0133             IndiGo         164                 15324  2513136
51     FL0052           SpiceJet         163                 13824  2253312
7      FL0008          Air India         157                 14173  2225161
176    FL0177            Vistara         124                 17306  2145944
36     FL0037            Vistara         184                 11614  2136976
108    FL0109           SpiceJet         129                 16390  2114310
107    FL0108             IndiGo         198                 10551  2089098
30     FL0031            Vistara         209                  9962  2082058

In [48]:
df.sort_values(["Airline", "Delay_Minutes"], ascending=[True, False]).head(10)[
    ["Airline", "Flight_ID", "Delay_Minutes", "Flight_Status"]
]

       Airline Flight_ID  Delay_Minutes Flight_Status
50   Air India    FL0051          110.0       Delayed
161  Air India    FL0162          110.0       Delayed
131  Air India    FL0132           75.0       Delayed
84   Air India    FL0085           35.0       Delayed
98   Air India    FL0099           35.0       Delayed
4    Air India    FL0005           20.0       Delayed
47   Air India    FL0048           20.0       Delayed
119  Air India    FL0120           20.0       Delayed
153  Air India    FL0154           20.0       Delayed
25   Air India    FL0026           12.0       On Time

In [49]:
airline_performance = df.groupby("Airline").agg(
    Total_Flights=("Flight_ID", "count"),
    Avg_Delay=("Delay_Minutes", "mean"),
    Total_Revenue=("Revenue", "sum"),
    Avg_Satisfaction=("Passenger_Satisfaction", "mean")
).round(2).sort_values("Avg_Delay", ascending=False)

airline_performance

                   Total_Flights  Avg_Delay  Total_Revenue  Avg_Satisfaction
Airline
IndiGo                        32      25.03       25709131              3.34
SpiceJet                      32      21.88       24195935              3.53
Air India                     24      20.38       16232418              3.75
Vistara                       37      17.62       28689467              3.38
Akasa Air                     31      13.94       18872059              3.42
Air India Express             24      11.29       23944164              3.67

In [50]:
weather_delay = df.groupby("Weather")["Delay_Minutes"].mean().round(2).sort_values(ascending=False)
weather_delay

Weather
Rain      21.19
Storm     19.43
Cloudy    18.45
Clear     18.03
Fog       15.34
Name: Delay_Minutes, dtype: float64

In [51]:
status_by_origin = df.groupby(["Origin", "Flight_Status"]).size().unstack(fill_value=0)
status_by_origin

Flight_Status  Cancelled  Delayed  On Time
Origin
Ahmedabad              1        3        8
Bengaluru              0        5       16
Chennai                0        2        7
Delhi                  4       17       22
Hyderabad              0        4        3
Jaipur                 0        2        6
Kochi                  1        3       10
Lucknow                0        6        5
Mumbai                 0       11       18
Pune                   0        1       10
Srinagar               1        5        9

In [52]:
df.groupby("Travel_Class")["Passenger_Satisfaction"].mean().round(2).sort_values(ascending=False)

Travel_Class
Premium Economy    3.69
Economy            3.46
Business           3.27
Name: Passenger_Satisfaction, dtype: float64

In [53]:
df.groupby("Aircraft")["Load_Factor_%"].mean().round(2).sort_values(ascending=False)

Aircraft
Airbus A321    68.89
Airbus A319    64.96
Airbus A320    58.92
Boeing 737     57.85
Name: Load_Factor_%, dtype: float64

In [54]:
df.groupby("Booking_Channel").agg(
    Bookings=("Flight_ID", "count"),
    Avg_Ticket_Price=("Average_Ticket_Price", "mean")
).round(2).sort_values("Bookings", ascending=False)

                      Bookings  Avg_Ticket_Price
Booking_Channel
Online Travel Portal        50           5636.28
Mobile App                  45           6637.24
Travel Agency               44           6223.89
Airline Website             41           5994.17

In [55]:
pd.crosstab(df["Airline"], df["Delay_Category"])

Delay_Category,Minor Delay (<=30 min),Moderate Delay (31-60 min),No Delay,Severe Delay (>60 min)
Airline,,,,
Air India,10,2,9,3
Air India Express,9,1,13,1
Akasa Air,10,5,14,2
IndiGo,10,4,13,5
SpiceJet,13,4,11,4
Vistara,11,6,17,3

**Q1. Which airline has the most delayed flights, and which has the best on-time performance?**

In [56]:
delay_share = df.groupby("Airline")["Flight_Status"].apply(
    lambda x: (x == "Delayed").sum() / len(x) * 100
).round(2).sort_values(ascending=False)

print("% of flights delayed, by airline:")
delay_share

% of flights delayed, by airline:

Airline
Air India            37.50
SpiceJet             37.50
Vistara              35.14
IndiGo               34.38
Akasa Air            25.81
Air India Express    25.00
Name: Flight_Status, dtype: float64

**Q2. Does weather meaningfully affect delay duration?**

In [57]:
weather_impact = df.groupby("Weather").agg(
    Avg_Delay=("Delay_Minutes", "mean"),
    Flights=("Flight_ID", "count")
).round(2).sort_values("Avg_Delay", ascending=False)

weather_impact

         Avg_Delay  Flights
Weather
Rain         21.19       43
Storm        19.43       30
Cloudy       18.45       38
Clear        18.03       34
Fog          15.34       35

**Q4. Is there a relationship between load factor and passenger satisfaction?**

In [58]:
correlation = df[["Load_Factor_%", "Passenger_Satisfaction", "Delay_Minutes",
                   "Average_Ticket_Price", "Avg_Baggage_Kg"]].corr()

correlation["Passenger_Satisfaction"].sort_values(ascending=False)

Passenger_Satisfaction    1.000000
Load_Factor_%             0.155561
Avg_Baggage_Kg            0.135294
Average_Ticket_Price      0.044299
Delay_Minutes            -0.065703
Name: Passenger_Satisfaction, dtype: float64

**Q6. Which month had the most flight activity and the highest average delay?**

In [59]:
monthly_summary = df.groupby("Month").agg(
    Flights=("Flight_ID", "count"),
    Avg_Delay=("Delay_Minutes", "mean")
).round(2)

month_order = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]
monthly_summary = monthly_summary.reindex([m for m in month_order if m in monthly_summary.index])

monthly_summary

          Flights  Avg_Delay
Month
January        29      22.10
February       28      22.75
March          33       9.39
April          35      24.69
May            30      15.80
June           25      16.76

1. **Cancellations are weather-linked at the data level** — every flight with a missing `Delay_Minutes` value was a cancelled flight, confirming cancellations are recorded separately from delay duration rather than as an extreme delay case.

2. **Delay performance varies clearly by airline** — some airlines (e.g. IndiGo and SpiceJet in this dataset) show a noticeably higher average delay and higher share of delayed flights than others (e.g. Air India Express and Akasa Air), suggesting real operational differences worth investigating further.

3. **Weather has a measurable but moderate effect on delays** — average delay minutes differ across weather conditions, with Rain and Storm associated with longer average delays than Clear or Fog conditions, though the gap is not enormous, implying other operational factors also drive delays.

4. **Load factor does not strongly predict satisfaction** — the correlation between `Load_Factor_%` and `Passenger_Satisfaction` is weak and positive, indicating a fuller flight doesn't necessarily mean an unhappier passenger in this dataset; satisfaction is likely driven more by service factors not captured here.

5. **Premium Economy passengers report the highest average satisfaction**, edging out both Business and Economy — a counter-intuitive finding, since Business class typically commands the highest price but does not have the highest satisfaction score.

6. **Route traffic is concentrated on a handful of city pairs** — a small number of Origin→Destination routes account for a disproportionate share of total flights, consistent with hub-and-spoke patterns around major cities like Delhi and Mumbai.