In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/Day8_Ecommerce_Sales_Dataset.csv')

print("Shape:", df.shape)
df.head()

Shape: (100, 13)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [6]:
orders_df = df[['Order_ID', 'Order_Date', 'Customer', 'City', 'Region',
                 'Quantity', 'Total_Sales', 'Payment_Method']].copy()

product_details_df = df[['Order_ID', 'Category', 'Product', 'Unit_Price',
                          'Discount_Percent', 'Rating']].copy()

print("orders_df:", orders_df.shape)
print("product_details_df:", product_details_df.shape)

orders_df.head()

orders_df: (100, 8)
product_details_df: (100, 6)

,Order_ID,Order_Date,Customer,City,Region,Quantity,Total_Sales,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,3,4497.00,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,1,2799.00,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,2,2038.30,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,4,9496.20,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,1,3134.05,UPI

In [7]:
product_details_df.head()

,Order_ID,Category,Product,Unit_Price,Discount_Percent,Rating
0,1001,Electronics,Wireless Headphones,1499,0,3.8
1,1002,Sports,Running Shoes,2799,0,4.1
2,1003,Electronics,Power Bank,1199,15,4.6
3,1004,Electronics,Mechanical Keyboard,2499,5,4.1
4,1005,Electronics,Smart Watch,3299,5,4.2

In [8]:
merged_df = pd.merge(orders_df, product_details_df, on='Order_ID', how='inner')

print("Shape after merge():", merged_df.shape)
assert merged_df.shape[0] == df.shape[0], "Row count changed after merge — check the join!"
merged_df.head()

Shape after merge(): (100, 13)

,Order_ID,Order_Date,Customer,City,Region,Quantity,Total_Sales,Payment_Method,Category,Product,Unit_Price,Discount_Percent,Rating
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,3,4497.00,Cash on Delivery,Electronics,Wireless Headphones,1499,0,3.8
1,1002,2026-01-24,Aditya Verma,Jammu,North,1,2799.00,Cash on Delivery,Sports,Running Shoes,2799,0,4.1
2,1003,2026-04-18,Sara Ahmed,Chennai,South,2,2038.30,Cash on Delivery,Electronics,Power Bank,1199,15,4.6
3,1004,2026-03-13,Kabir Ali,Lucknow,North,4,9496.20,Debit Card,Electronics,Mechanical Keyboard,2499,5,4.1
4,1005,2026-03-30,Priya Menon,Jammu,North,1,3134.05,UPI,Electronics,Smart Watch,3299,5,4.2

In [9]:
batch_north_east = merged_df[merged_df['Region'].isin(['North', 'East'])]
batch_south_west = merged_df[merged_df['Region'].isin(['South', 'West'])]

print("North & East batch:", batch_north_east.shape)
print("South & West batch:", batch_south_west.shape)

combined_df = pd.concat([batch_north_east, batch_south_west], axis=0, ignore_index=True)

print("Shape after concat():", combined_df.shape)
assert combined_df.shape[0] == merged_df.shape[0], "Row count mismatch after concat()!"
assert set(combined_df['Order_ID']) == set(merged_df['Order_ID']), "Order_IDs don't match after concat()!"

combined_df.head()

North & East batch: (46, 13)
South & West batch: (54, 13)
Shape after concat(): (100, 13)

,Order_ID,Order_Date,Customer,City,Region,Quantity,Total_Sales,Payment_Method,Category,Product,Unit_Price,Discount_Percent,Rating
0,1002,2026-01-24,Aditya Verma,Jammu,North,1,2799.00,Cash on Delivery,Sports,Running Shoes,2799,0,4.1
1,1004,2026-03-13,Kabir Ali,Lucknow,North,4,9496.20,Debit Card,Electronics,Mechanical Keyboard,2499,5,4.1
2,1005,2026-03-30,Priya Menon,Jammu,North,1,3134.05,UPI,Electronics,Smart Watch,3299,5,4.2
3,1007,2026-01-12,Alina Shah,Jaipur,North,2,1398.00,Debit Card,Home & Kitchen,Water Bottle,699,0,4.1
4,1008,2026-04-27,Aman Kumar,Jammu,North,4,6076.20,Credit Card,Clothing,Hoodie,1599,5,4.3

In [10]:
combined_df['Order_Date'] = pd.to_datetime(combined_df['Order_Date'])

combined_df['Order_Year'] = combined_df['Order_Date'].dt.year
combined_df['Order_Month'] = combined_df['Order_Date'].dt.month
combined_df['Order_Month_Name'] = combined_df['Order_Date'].dt.month_name()
combined_df['Order_Day'] = combined_df['Order_Date'].dt.day
combined_df['Order_DayOfWeek'] = combined_df['Order_Date'].dt.day_name()
combined_df['Order_Quarter'] = combined_df['Order_Date'].dt.quarter
combined_df['Is_Weekend'] = combined_df['Order_Date'].dt.dayofweek.apply(lambda d: d >= 5)

combined_df[['Order_ID', 'Order_Date', 'Order_Year', 'Order_Month_Name',
             'Order_Day', 'Order_DayOfWeek', 'Order_Quarter', 'Is_Weekend']].head()

,Order_ID,Order_Date,Order_Year,Order_Month_Name,Order_Day,Order_DayOfWeek,Order_Quarter,Is_Weekend
0,1002,2026-01-24,2026,January,24,Saturday,1,True
1,1004,2026-03-13,2026,March,13,Friday,1,False
2,1005,2026-03-30,2026,March,30,Monday,1,False
3,1007,2026-01-12,2026,January,12,Monday,1,False
4,1008,2026-04-27,2026,April,27,Monday,2,False

In [11]:
combined_df['Discount_Amount'] = combined_df.apply(
    lambda row: round(row['Unit_Price'] * row['Quantity'] * row['Discount_Percent'] / 100, 2),
    axis=1
)

def price_category(price):
    if price < 1000:
        return 'Budget'
    elif price < 2500:
        return 'Mid-Range'
    else:
        return 'Premium'

combined_df['Price_Category'] = combined_df['Unit_Price'].apply(price_category)

def value_segment(total):
    if total < 2000:
        return 'Low Value'
    elif total < 6000:
        return 'Medium Value'
    else:
        return 'High Value'

combined_df['Customer_Value_Segment'] = combined_df['Total_Sales'].apply(value_segment)

def rating_label(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    elif rating >= 3.5:
        return 'Average'
    else:
        return 'Poor'

combined_df['Rating_Label'] = combined_df['Rating'].apply(rating_label)

combined_df[['Order_ID', 'Unit_Price', 'Price_Category', 'Discount_Amount',
             'Total_Sales', 'Customer_Value_Segment', 'Rating', 'Rating_Label']].head()

,Order_ID,Unit_Price,Price_Category,Discount_Amount,Total_Sales,Customer_Value_Segment,Rating,Rating_Label
0,1002,2799,Premium,0.00,2799.00,Medium Value,4.1,Good
1,1004,2499,Mid-Range,499.80,9496.20,High Value,4.1,Good
2,1005,3299,Premium,164.95,3134.05,Medium Value,4.2,Good
3,1007,699,Budget,0.00,1398.00,Low Value,4.1,Good
4,1008,1599,Mid-Range,319.80,6076.20,High Value,4.3,Good

In [12]:
final_columns = [
    'Order_ID', 'Order_Date', 'Order_Year', 'Order_Month', 'Order_Month_Name',
    'Order_Day', 'Order_DayOfWeek', 'Order_Quarter', 'Is_Weekend',
    'Customer', 'City', 'Region',
    'Category', 'Product', 'Price_Category',
    'Quantity', 'Unit_Price', 'Discount_Percent', 'Discount_Amount',
    'Total_Sales', 'Customer_Value_Segment',
    'Rating', 'Rating_Label', 'Payment_Method'
]

final_df = combined_df[final_columns].sort_values('Order_Date').reset_index(drop=True)

print("Final shape:", final_df.shape)
final_df.head(10)

Final shape: (100, 24)

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_DayOfWeek,Order_Quarter,Is_Weekend,Customer,...,Price_Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Total_Sales,Customer_Value_Segment,Rating,Rating_Label,Payment_Method
0,1059,2026-01-01,2026,1,January,1,Thursday,1,False,Mehak Bhat,...,Mid-Range,4,2499,15,1499.40,8496.60,High Value,4.2,Good,Credit Card
1,1025,2026-01-02,2026,1,January,2,Friday,1,False,Rohan Mehta,...,Budget,5,799,0,0.00,3995.00,Medium Value,5.0,Excellent,UPI
2,1046,2026-01-03,2026,1,January,3,Saturday,1,True,Ananya Singh,...,Budget,4,499,15,299.40,1696.60,Low Value,3.8,Average,Credit Card
3,1098,2026-01-04,2026,1,January,4,Sunday,1,True,Yusuf Dar,...,Mid-Range,4,1499,0,0.00,5996.00,Medium Value,4.2,Good,Net Banking
4,1031,2026-01-04,2026,1,January,4,Sunday,1,True,Rohan Mehta,...,Budget,1,899,15,134.85,764.15,Low Value,4.1,Good,Credit Card
5,1078,2026-01-05,2026,1,January,5,Monday,1,False,Maryam Khan,...,Budget,1,999,10,99.90,899.10,Low Value,4.7,Excellent,UPI
6,1053,2026-01-08,2026,1,January,8,Thursday,1,False,Ananya Singh,...,Premium,5,2799,5,699.75,13295.25,High Value,4.2,Good,Credit Card
7,1007,2026-01-12,2026,1,January,12,Monday,1,False,Alina Shah,...,Budget,2,699,0,0.00,1398.00,Low Value,4.1,Good,Debit Card
8,1032,2026-01-16,2026,1,January,16,Friday,1,False,Ishita Gupta,...,Budget,2,599,10,119.80,1078.20,Low Value,4.5,Excellent,UPI
9,1071,2026-01-16,2026,1,January,16,Friday,1,False,Aditya Verma,...,Budget,4,699,10,279.60,2516.40,Medium Value,4.5,Excellent,Net Banking